# Generated by Django 2.2.14 on 2020-07-28 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0002_campaignadminstrator_candidate_comitteemember_communicationofficer_voter'),
        ('adminstration', '0002_comittee_electioncard'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncard',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_management.Candidate'),
        ),
        migrations.AddField(
            model_name='electioncard',
            name='communication_officer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_management.CommunicationOfficer'),
        ),
        migrations.AddField(
            model_name='electioncard',
            name='voter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_management.Voter'),
        ),
        migrations.AddField(
            model_name='comittee',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Address'),
        ),
        migrations.AddField(
            model_name='comittee',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comittee_candidate', to='users_management.Candidate'),
        ),
        migrations.AddField(
            model_name='comittee',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comittee_manager', to='users_management.ComitteeMember'),
        ),
    ]
