# Generated by Django 2.2.14 on 2020-08-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0003_auto_20200728_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comittee',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comittee_manager', to='users_management.ComitteeMember'),
        ),
    ]
