# Generated by Django 2.2.14 on 2020-08-15 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0005_remove_comittee_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comittee',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comittee_candidate', to='users_management.Candidate'),
        ),
    ]
