# Generated by Django 2.2.14 on 2020-08-15 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0018_auto_20200814_1056'),
        ('adminstration', '0006_auto_20200815_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='comittee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comittee_manager', to='users_management.ComitteeMember'),
        ),
    ]
