# Generated by Django 2.2.14 on 2020-08-16 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_electionaddress'),
        ('adminstration', '0007_comittee_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionlist',
            name='address',
        ),
        migrations.AddField(
            model_name='electionlist',
            name='election_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.ElectionAddress'),
        ),
    ]
