# Generated by Django 2.2.14 on 2020-08-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0009_comittee_address_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comittee',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address'),
        ),
    ]
