# Generated by Django 2.2.14 on 2020-08-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200815_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Department')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Governorate')),
            ],
        ),
    ]
