# Generated by Django 2.2.14 on 2020-07-28 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0002_comittee_electioncard'),
        ('users_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('comittees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comittees_list', to='adminstration.Comittee')),
                ('election_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminstration.ElectionList')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_management.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_status', models.CharField(choices=[('Voting', 'Voting'), ('Not_sure', 'Not sure'), ('Not_voting', 'Not voting')], max_length=50)),
                ('is_identifier', models.BooleanField(default=False)),
                ('followed_up', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('voting_id', models.CharField(max_length=50, null=True)),
                ('identiefier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_management.Voter')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_management.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comittee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminstration.Comittee')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_management.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ComitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('is_manager', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.Candidate')),
                ('comittee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminstration.Comittee')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_management.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAdminstrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.Candidate')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_management.UserProfile')),
            ],
        ),
    ]
