# Generated by Django 2.2.14 on 2020-07-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0003_remove_candidate_comittees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('create_commitee', 'Can create commitee'), ('add_committee_member', 'can add commitee member')]},
        ),
    ]
