# Generated by Django 2.2.14 on 2020-08-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0005_auto_20200803_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comitteemember',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comitteemember',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
