# Generated by Django 2.2.14 on 2020-08-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0006_auto_20200803_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comitteemember',
            name='comittee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstration.Comittee'),
        ),
    ]
