# Generated by Django 2.2.14 on 2020-08-03 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0007_auto_20200803_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVoterssPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_voter', models.BooleanField()),
                ('can_update_voter', models.BooleanField()),
                ('can_create_voter', models.BooleanField()),
                ('can_remove_voter', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomReportsPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_report', models.BooleanField()),
                ('can_update_report', models.BooleanField()),
                ('can_create_report', models.BooleanField()),
                ('can_remove_report', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomMembersPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_member', models.BooleanField()),
                ('can_update_member', models.BooleanField()),
                ('can_create_member', models.BooleanField()),
                ('can_remove_member', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomComitteePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_comittee', models.BooleanField()),
                ('can_update_comittee', models.BooleanField()),
                ('can_create_comittee', models.BooleanField()),
                ('can_remove_comittee', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.UserProfile')),
            ],
        ),
    ]
