# Generated by Django 2.2.14 on 2020-08-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0008_customcomitteepermission_custommemberspermissions_customreportspermissions_customvotersspermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_management.Candidate'),
        ),
    ]
