# Generated by Django 2.2.14 on 2020-08-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0009_voter_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='vote_status',
            field=models.CharField(choices=[('Voting', 'Voting'), ('Not_sure', 'Not sure'), ('Not_voting', 'Not voting')], max_length=50, null=True),
        ),
    ]
