# Generated by Django 2.2.14 on 2020-08-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0010_auto_20200805_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_management.Candidate'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='identiefier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_management.Voter'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
