# Generated by Django 2.2.14 on 2020-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0011_auto_20200805_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
