# Generated by Django 2.2.14 on 2020-08-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0012_workfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_management.WorkField'),
        ),
    ]
