# Generated by Django 2.2.14 on 2020-08-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0014_userprofile_name_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name_string',
        ),
    ]
