# Generated by Django 2.2.14 on 2020-08-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0015_remove_userprofile_name_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name_string',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
