# Generated by Django 2.2.14 on 2020-08-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0016_userprofile_name_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='has_elc_card',
            field=models.BooleanField(default=False),
        ),
    ]
