# Generated by Django 2.2.14 on 2020-08-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0017_voter_has_elc_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='identiefier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_management.Voter'),
        ),
    ]
