# Generated by Django 2.2.14 on 2020-08-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0018_auto_20200814_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='related_comittee_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_management.ComitteeMember'),
        ),
    ]
