# Generated by Django 2.2.14 on 2020-08-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0020_voter_election_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
