# Generated by Django 2.2.14 on 2020-08-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0022_comitteemember_election_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='comitteemember',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
