# Generated by Django 2.2.14 on 2020-08-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0027_voter_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
