# Generated by Django 2.2.14 on 2020-08-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0028_auto_20200822_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images'),
        ),
    ]
