# Generated by Django 2.2.14 on 2020-09-06 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0034_auto_20200902_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='communication_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_offices', to='users_management.ComitteeMember'),
        ),
        migrations.AddField(
            model_name='voter',
            name='election_box_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='election_box_officer', to='users_management.ComitteeMember'),
        ),
    ]
