# Generated by Django 2.2.14 on 2020-09-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0035_auto_20200906_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='communication_officer',
        ),
    ]
