# Generated by Django 2.2.14 on 2020-09-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200907_1552'),
        ('users_management', '0036_remove_voter_communication_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='residence_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Residence'),
        ),
    ]
