# Generated by Django 2.2.14 on 2020-09-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0037_voter_residence_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='election_place',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
