# Generated by Django 2.2.14 on 2020-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0038_auto_20200908_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
