# Generated by Django 2.2.14 on 2020-09-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0039_auto_20200908_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='full_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
